### PR TITLE
Code structure and EFCore project + test

### PR DESCRIPTION
**Pull request by Tasteful**
Is dependent of https://github.com/AutoMapper/AutoMapper.Collection/pull/106

Only master branch exist so cant push to any other.

https://github.com/AutoMapper/AutoMapper.Collection/issues/86

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
AppVoyer said some tests failed.  Don't know if that's because you need the update to AM.Collections with the service ctor fix.

**Comment by TylerCarlson1** [comment]
Merged the PR so hopefully that can fix the test now.

**Comment by Tasteful** [comment]
It's the https://github.com/AutoMapper/AutoMapper.Collection/pull/102 that will fix the versioning that is wrong on myget feed.

**Comment by TylerCarlson1** [comment]
Ok merged.

**Comment by Tasteful** [comment]
This is now using a prerelease of AM.Collection that have build number 4.0.0-ci-00082, the 4.0.0 package is already released so it can be hard to get people to test this and get correct nuget-package versions down. AM.Collection should probably get the `version.prop` file updated to `4.1.0` (minor version due to new features, (value type mapping) that not should be breaking) I think. When that exists on myget we can change the AM-reference to use the new version and let developers start testing that one from the myget-feed.

**Comment by TylerCarlson1** [comment]
Updated to 4.1.0 so you should be able to update the reference so people can test from myget feed.

I still need to double check the code myself before committing, but all should be good.

Thanks @Tasteful for setting up EFCore and translating it to a new solution.

**Comment by Tasteful** [comment]
@TylerCarlson1 Can you push a development branch into the repo also so the PR can be changed to target that branch instead. Otherwise I think CI will make an public release on nuget when this PR is completed.

**Comment by TylerCarlson1** [comment]
Updated.  Now it should go into MyGet

**Comment by Tasteful** [comment]
It is only build from development that is going to the MyGet-feed, builds from master is pushed directly to nuget.org. This regarding to the `appveyor.yaml` file. If you want the nuget packaes from the PR you need to fetch them from https://ci.appveyor.com/project/TylerCarlson1/automapper-collection-efcore/build/1-mvowmitu/artifacts

**Comment by Tasteful** [comment]
So when this PR is completed the dev branch will be updated and start a new build. That build will build a new package into myget.

**Comment by Tasteful** [comment]
I can't think of any other parts that need to be done before it can be merged. I think that new cases or functions can be added after developers start using it. It should be good with some early-adopters for it to see that everything is working as it should in real cases.

**Comment by TylerCarlson1** [comment]
Having issues pushing the symbols over to MyGet.  @jbogard any ideas on why it's happening?
Changed AppVoyer build worker image to 2017 from 2015 and skip symbols is not false on YAML.

**Comment by Tasteful** [comment]
If we check the AM.Collection it using AppVeyor account `jbogard`, the new AM.Collection.EFCore is using account `TylerCarlson1`. Thats will make the encrypted keys in the yaml-file to not work.

Either the keys need to be updated in the yaml-file or the server hooks need be replaced with new one for `jbogard` account.

@TylerCarlson1 @jbogard

**Comment by TylerCarlson1** [comment]
Yea I made one for AutoMapper.Collection and I guess @jbogard copied it over to his account and it works on that one and not the one I made.  It's last build was about 2 years old so I completely forgot what I had to do to get this working last time.

**Comment by Thorgard** [comment]
@Tasteful any chance to publish this on NuGet?

**Comment by Tasteful** [comment]
It's on @TylerCarlson1 to fix that the build system will work so that will push the packages first up to the MyGet-feed so it can be tested before it is pushed out on NuGet.

**Comment by TylerCarlson1** [comment]
I thought @jbogard would help but I guess that's not the case.  I'll have to figure out the API key thing myself, some time this week.

**Comment by jbogard** [comment]
Ha! No I just had this repo muted. Whoops.

So I just need to add this build in my AppVeyor?

**Comment by TylerCarlson1** [comment]
Yea that should be it.  That's what happened with Automapper.Collection I think.

**Comment by Tasteful** [comment]
@Thorgard Now you can find the package on MyGet (https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Collection.EntityFrameworkCore)

**Pull request merged**
