### PR TITLE
Made less coupling between this package and DBContext

### PR DESCRIPTION
**Pull request by redradist**
Made less coupling between this package and DBContext that allows to use existing DBContext in configuration

### CODE REVIEW

**Comment by redradist** [comment]
Very strange, on my machine all tests are passed succesfully

**Comment by Tasteful** [comment]
No, I haven't access for integrations, but is probably that a lot of package versions are upgraded, they are not needed to be version 3 and instead if they are version 2 (as before) the package is compatible with more users.

I was looking at the PR in general and don't understand what the improvement should be, you can today you can call `cfg.UseEntityFrameworkCoreModel<DbContext>(alreadyCreatedModel.Model)` to map from the already existing model.

**Comment by redradist** [comment]
> 
> 
> No, I haven't access for integrations, but is probably that a lot of package versions are upgraded, they are not needed to be version 3 and instead if they are version 2 (as before) the package is compatible with more users.
> 
> I was looking at the PR in general and don't understand what the improvement should be, you can today you can call `cfg.UseEntityFrameworkCoreModel<DbContext>(alreadyCreatedModel.Model)` to map from the already existing model.

@Tasteful Okay, agree, I have removed extra method

**Comment by redradist** [comment]
@Tasteful AutoMapper packages at least should be synchronized because there is difference in 2 major versions and this means that in AutoMapper could be fixed lots of bugs

**Pull request closed without merging**
