### PR TITLE
Feature - Added options as an optional parameter of InsertOrUpdate

### PR DESCRIPTION
**Pull request by Luk164**
I needed this feature because of a M-M saving conflict while using EF7 and I thought others would appreciate it as well.

### CODE REVIEW

**Comment by ahmed-abdelrazek** [comment]
is this project dead?!

**Comment by Luk164** [comment]
> is this project dead?!

I guess so 🙁

**Comment by Luk164** [comment]
@lbargaoanu Hey, any reason to refuse the PR so I could rework it?

**Comment by lbargaoanu** [comment]
I don't want to get into it. But if someone else does, they can reopen and review.

**Pull request closed without merging**
