### PR TITLE
enhance Insert and Remove tests for better test coverage and repeatab…

### PR DESCRIPTION
**Pull request by DickBaker**
…ility
Fix for #39

### CODE REVIEW

**Review by Tasteful — APPROVED** [review]
@DickBaker Please, rebase and fix the conflict

**Comment by DickBaker** [comment]
> @DickBaker Please, rebase and fix the conflict

sorry Tasteful I am newbie to the GH flow. I cannot see what the conflicts are (GH on my browser says "
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
").  I tried a rebase on my local branch [log below] but afterwards there are no Changes (maybe this is normal for successful rebase?) and Commit still greyed out. I am unclear how to Commit or if I must submit new PR.
 => Pls advise what action I need to take to move us forward (thanks for moral "approval" anyway!)

Switched to branch 'PersistRemove_enhance_tests'
Your branch is up to date with 'origin/PersistRemove_enhance_tests'.
Checked out refs/heads/PersistRemove_enhance_tests
Rebasing current branch onto refs/remotes/origin/master.
Rebase - Current branch PersistRemove_enhance_tests is up to date.
Successfully rebased the current branch.

**Comment by Tasteful** [comment]
Everyone is newbie some times and it is little hard to get into the GH flow but I will try to help you. We are happy for all help we can get to make improvements in different ways.

I think you today have make a fork of the AutoMapper.Collection.EFCore repository that is the only one that you have cloned to your lokal computer. Then the steps will be something like this (commands executed on the command line from your local repository folder):

1. Add AutoMapper.Collection.EFCore as an upstream source, you will use this to sync changes from this repository `git remote add upstream https://github.com/AutoMapper/AutoMapper.Collection.EFCore.git`
2. Sync the upstream to your local computer `git fetch upstream`, now all changes is in the upstream prefixed remote branch
3. Rebase on the `upstream/master` branch (`master` is in this case the target branch for the PR) `git rebase upstream/master`, resolve conflicts.
4. Check that everything is running on local computer and test is passing.
5. Push the change to your github fork `git push -f` (the `-f` will make the push a force-push that in most case is needed when you have done an rebase).

Now everything should be updated and the PR have new files.

Note: When you changing back to your master branch the branch will still be outdated and you need to execute `git rebase upstream/master` and `git push -f` to update your fork with the changes from the remote master.

**Comment by DickBaker** [comment]
Collaborators (Tyler/Tasteful/etc) please intervene to force conflict resolution! I have moved my new code to the bottom to avoid false-diff-match, but renaming the 4 test method names (to better match what they ACTUALLY do) is unacceptable to GH which is being particularly anal. Hope you guys concur and can bulldoze it through as I have more PRs I want to submit but after this friction I don't want to re-edit PR41 (and raise new PRxx)  until dust settles on this PR40. Thanks, Dick </rant>

**Review by DickBaker — COMMENTED** [review]
re-commented in case my earlier plea for Collab help unheard (apologies if dup) ...

Collaborators (Tyler/Tasteful/etc) please intervene to force conflict resolution! I have moved my new code to the bottom to avoid false-diff-match, but renaming the 4 test method names (to better match what they ACTUALLY do) is unacceptable to GH which is being particularly anal. Hope you guys concur and can bulldoze it through as I have more PRs I want to submit but after this friction I don't want to re-edit PR41 (and raise new PRxx) until dust settles on this PR40. Thanks, Dick

**Pull request closed without merging**
