### PR TITLE
Upgrade to use AutoMapper 8

### PR DESCRIPTION
**Pull request by Tasteful**

### CODE REVIEW

**Comment by Tasteful** [comment]
#2

**Comment by Tasteful** [comment]
Blocking
* https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/issues/77
* https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/pull/20

**Comment by TylerCarlson1** [comment]
@Tasteful Has the updates to AM resolve the Blocking?

**Comment by jbogard** [comment]
AutoMapper.Collection and friends are now published. Will take a few
minutes for their index to update.

**Comment by Tasteful** [comment]
@TylerCarlson1 Everything is now ready to be merged into development. Not sure if we should bump version to `1.0.0` before merging into master and tagging for the release

**Comment by TylerCarlson1** [comment]
@Tasteful I'm less sure, but if you think it's fine for a 1.0.0 for a nuget release I'm all for it.

**Comment by jbogard** [comment]
Is that a completely new package?

**Comment by jbogard** [comment]
Because if so it might need to be named AutoMapper.Extensions.*

**Comment by TylerCarlson1** [comment]
Was thinking AutoMapper.Collection.EFCore or AutoMapper.Collection.EntityFrameworkCore which is what it is in MyGet.

If you want to follow that convention then I would suggest AutoMapper.Collection.Extensions.EFCore.
@Tasteful Not sure how you feel but I'm fine with changing the name to be consistent with the new system.

**Comment by jbogard** [comment]
I think you have to start it with Extensions

**Comment by jbogard** [comment]
What’s the error though? I can’t see that feed.

**Comment by TylerCarlson1** [comment]
https://ci.appveyor.com/project/TylerCarlson1/automapper-collection-efcore/builds/20445749

Ending lines if can't read it.
```
Uploading artifacts...
[1/2] artifacts\AutoMapper.Collection.EntityFrameworkCore.0.1.0-ci-00005.nupkg (12,462 bytes)...100%
[2/2] artifacts\AutoMapper.Collection.EntityFrameworkCore.0.1.0-ci-00005.symbols.nupkg (15,716 bytes)...100%
"NuGet" deployment for branch "master" has been skipped because current branch is "development"
"NuGet" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
Deploying using NuGet provider
Provider setting not found or it's value is empty. If secure setting is used please check that value was encrypted (or YAML was exported) while being logged under correct account.
Parameter name: api_key
```

It's possible I didn't set the up correctly and it's trying to go to nuget, but I doubt it.

**Pull request merged**
